import Link from 'next/link';
import { notFound } from 'next/navigation';
import NewsCard from '@/components/NewsCard';
import { getSupabaseAdmin, type SearchHistoryRow } from '@/lib/supabase';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

interface PageProps {
  params: { id: string };
}

async function getSearchById(id: string): Promise<SearchHistoryRow | null> {
  try {
    const supabase = getSupabaseAdmin();
    const { data, error } = await supabase
      .from('news_searches')
      .select('*')
      .eq('id', id)
      .maybeSingle();
    if (error) {
      console.error('[history/[id]] supabase error:', error);
      return null;
    }
    return (data as SearchHistoryRow) ?? null;
  } catch (err) {
    console.error('[history/[id]] exception:', err);
    return null;
  }
}

export default async function HistoryDetailPage({ params }: PageProps) {
  const entry = await getSearchById(params.id);
  if (!entry) notFound();

  const created = new Date(entry.created_at);

  return (
    <div className="flex flex-col gap-8">
      <header className="flex flex-col gap-3">
        <Link
          href="/history"
          className="inline-flex w-fit items-center gap-1 text-sm text-white/50 transition hover:text-accent-300"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-4 w-4"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="m15 18-6-6 6-6" />
          </svg>
          All searches
        </Link>

        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <p className="text-xs uppercase tracking-wider text-accent-400">
              Saved search
            </p>
            <h1 className="mt-1 text-3xl font-bold tracking-tight text-white">
              {entry.keyword}
            </h1>
          </div>
          <div className="rounded-lg border border-border bg-card px-4 py-2 text-right">
            <p className="text-xs text-white/40">Run on</p>
            <p className="text-sm font-medium text-white/90">
              {created.toLocaleString(undefined, {
                month: 'short',
                day: 'numeric',
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit',
              })}
            </p>
          </div>
        </div>

        <p className="text-sm text-white/50">
          {entry.result_count} article{entry.result_count === 1 ? '' : 's'}{' '}
          captured at search time. Summaries generated by{' '}
          <span className="text-accent-300">gpt-4o-mini</span>.
        </p>
      </header>

      {Array.isArray(entry.results) && entry.results.length > 0 ? (
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {entry.results.map((article, i) => (
            <NewsCard
              key={(article.url || '') + i}
              article={article}
              index={i}
            />
          ))}
        </div>
      ) : (
        <div className="rounded-xl border border-dashed border-border bg-card/40 px-6 py-12 text-center text-sm text-white/40">
          No results were saved for this search.
        </div>
      )}

      <div className="flex justify-center pt-6">
        <Link
          href={`/?q=${encodeURIComponent(entry.keyword)}`}
          className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-br from-accent-500 to-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow-md shadow-accent-900/40 transition hover:from-accent-400 hover:to-indigo-500"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-4 w-4"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M3 12a9 9 0 1 0 9-9" />
            <path d="M3 4v5h5" />
          </svg>
          Re-run this search
        </Link>
      </div>
    </div>
  );
}
