/**
 * English message catalog — the source of truth for i18n.
 *
 * The German catalog (de.ts) is typed as `typeof en`, so the compiler rejects
 * any missing or misspelled key. Values may contain {named} placeholders that
 * translate()'s params argument fills in.
 */
export const en = {
  common: {
    appName: 'NewsPulse AI',
    search: 'Search',
    history: 'History',
    dashboard: 'Dashboard',
    language: 'Language',
  },
  nav: {
    brandSuffix: 'AI',
  },
  home: {
    badge: 'AI-Powered News Intelligence',
    // The hero headline is three staccato verbs; the last is highlighted.
    heroSearch: 'Search.',
    heroScrape: 'Scrape.',
    heroSummarize: 'Summarize.',
    subtitle:
      'NewsPulse AI scrapes the latest articles from across the web and generates concise, neutral summaries — so you can stay informed in seconds.',
    inputPlaceholder: 'Try "AI regulation", "SpaceX", "climate summit"…',
    searchButton: 'Search',
    searching: 'Searching…',
    tryOneOfThese: 'Try one of these:',
    demoBanner:
      'Running in demo mode — results are sample data. Configure API keys for real news search.',
    validationEmpty: 'Please enter a keyword to search.',
    errorGeneric: 'Something went wrong.',
    searchFailed: 'Search failed ({status})',
    resultsFor_one: '{count} result for "{query}"',
    resultsFor_other: '{count} results for "{query}"',
    summariesBy: 'Summaries by {model}',
    noResultsTitle: 'No results for "{query}"',
    noResultsDescription: 'Try a different keyword or a broader topic.',
  },
  card: {
    aiSummary: 'AI-generated summary',
    read: 'Read',
    openInNewTab: 'Open article in new tab',
  },
  footer: {
    builtWith: 'Built with Next.js · Firecrawl · OpenAI · Supabase ·',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
  },
  history: {
    title: 'Search History',
    subtitle: "Every search you've run on NewsPulse AI, stored in Supabase.",
    refresh: 'Refresh',
    refreshTitle: 'Refresh search history',
    clear: 'Clear History',
    emptyTitle: 'No searches yet',
    emptyDescription: 'Run your first search and it will show up here.',
    emptyCta: 'Start searching',
    colKeyword: 'Keyword',
    colDate: 'Date Searched',
    colArticles: 'Articles Found',
    colActions: 'Actions',
    expand: 'Expand',
    collapse: 'Collapse',
    viewResults: 'View Results',
    hide: 'Hide',
    rerun: 'Re-run',
    rerunTitle: 'Re-run this search',
    openSavedSearch: 'Open this saved search',
    delete: 'Delete',
    deleteTitle: 'Delete this saved search',
    deleteAria: 'Delete saved search "{keyword}"',
    noSavedResults: 'No saved results for this search.',
    confirmClearAll: "Delete all {count} saved searches? This can't be undone.",
    confirmDeleteOne: 'Delete the saved search "{keyword}"?',
    adminTokenPrompt:
      'Deleting is protected on this deployment. Enter the admin token:',
    failedLoad: 'Failed to load history.',
    failedClear: 'Failed to clear history.',
    failedDelete: 'Failed to delete search.',
    failed: 'Failed ({status})',
    deleteFailed: 'Delete failed ({status})',
  },
  detail: {
    allSearches: 'All searches',
    savedSearch: 'Saved search',
    runOn: 'Run on',
    articlesCaptured_one:
      '{count} article captured at search time. Summaries generated by {model}.',
    articlesCaptured_other:
      '{count} articles captured at search time. Summaries generated by {model}.',
    noResultsSaved: 'No results were saved for this search.',
    rerun: 'Re-run this search',
  },
} as const;

/**
 * Widen the `as const` literal types (which pin exact English strings) to
 * plain `string`, while preserving the exact key structure. This lets the
 * German catalog supply different values yet still be checked for the same
 * shape — a missing or misspelled key stays a compile error.
 */
type Widen<T> = {
  [K in keyof T]: T[K] extends string ? string : Widen<T[K]>;
};

export type Messages = Widen<typeof en>;
